### ISSUE TITLE
添加氣體

### ISSUE THREAD

**Issue by Grey-Wind** [EmptyDreams/ModernIndustry#2]
氧氣
二氧化碳
一氧化碳
氮氣
氦氣
氫氣

臭氧？
氯氣？
二氧化硫？

**Comment by EmptyDreams** [comment]
气体的设计就比较复杂了，得考虑很多：

1. 如何产生气体
2. 如何处理已产生的气体
3. 气体排放到世界中会产生什么效果
4. 不同气体能否混合
5. 如何收集在世界中的气体
6. 等等……

这些都不是直接说我想添加 xxx 气体能够概括的，设计气体方块之前要先设计总体的系统框架，但是目前我还没有把相关的东西设计出来，具体的要等后面再详细规划。
